---
title: "R Tips + Functions"
format: 
  html:
    grid:
      body-width: 1200px
    theme: morph
date: last-modified
toc: true
execute: 
  output: true
  echo: true
  warning: false
  message: false
---

# Packages

```{r Load Packages}
library(tidyverse)
library(googledrive)
library(janitor)
library(here)
library(ggthemes)
# library(ggchicklet)
library(nflplotR)
library(scales)
library(skimr)
library(gtsummary)
library(dataReporter)
library(pointblank)

```

# R Functions

## General

+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| Function                                                   | Package         | Purpose / Use                                                                                                          | Lesson / Additional Resources                                                         |
+============================================================+=================+========================================================================================================================+=======================================================================================+
| `setwd()`                                                  |                 | sets working directory                                                                                                 | Week 3: session                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `getwd()`                                                  |                 | displays working directory                                                                                             | Week 4: session                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `here()`                                                   | here            | returns root of project, which can be inserted into file path: `read_csv(here("file.csv")`                             | Week 4: session                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `read_csv(path = "")`                                      | tidyverse       | imports csv                                                                                                            | Week 1: Import Data                                                                   |
|                                                            |                 |                                                                                                                        |                                                                                       |
|                                                            |                 | -   additional arguments can:                                                                                          | Week 1: Import Our Data Again                                                         |
|                                                            |                 |     -   specify values to treat as NA --- `na = c("*", "-", "--", "Prefer not to answer")`                             |                                                                                       |
|                                                            |                 |     -   manually set variable types --- `col_types = cols(varname = "type")` where c = character, n = number, D = date |                                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `read_excel(path = "")`                                    | readxl          | imports excel                                                                                                          | Week 7: Downloading and Importing Data                                                |
|                                                            |                 |                                                                                                                        |                                                                                       |
|                                                            |                 | -   additional arguments can:                                                                                          |                                                                                       |
|                                                            |                 |     -   specify values to treat as NA --- `na = c("*", "-", "--", "Prefer not to answer")`                             |                                                                                       |
|                                                            |                 |     -   specify sheet to import --- `sheet = "sheetname"`                                                              |                                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `read_stata()`                                             | haven/tidyverse | imports stata .dta files                                                                                               | [Bonus video: Labelled Variables](https://muse.ai/vt/7ZLmAfZ-SPSS-Labelled-Variables) |
|                                                            |                 |                                                                                                                        |                                                                                       |
|                                                            |                 |                                                                                                                        | [Documentation](https://haven.tidyverse.org/reference/read_dta.html)                  |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `clean_names()`                                            | janitor         | removes spaces and caps from var names; use with read_csv() or read_excel()                                            | Week 7: Downloading and Importing Data                                                |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `glimpse(object name)`                                     |                 | presents transposed data in console pane                                                                               | Week 1: Examine our Data                                                              |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `view(object name)`                                        |                 | opens data object in new tab                                                                                           | Week 1: Examine our Data                                                              |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `skim(object name)`                                        | skimr           | generates summary of data in console pane -- \# rows/columns, list of vars by type w/ summary stats                    | Week 1: Examine our Data                                                              |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `tbl_summary(object name)`                                 | gtsummary       | generates summary of data in viewer pane w/ summary stats                                                              |                                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `makeDataReport(object name)`                              | dataReporter    | generates PDF data summary w/ summary stats, var types, histograms                                                     |                                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `scan_data(object name)`                                   | pointblank      | generates overview of data in viewer pane, w/ details/summary stats that can be toggled on/off                         |                                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `drive_auth()`                                             | googlesheets4   | log in to google drive account                                                                                         | Week 6 session                                                                        |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `drive_read_string_(file = "name.extension") |>read_csv()` | googlesheets4   | identifies file in google drive and converts to csv object                                                             | Week 6 session                                                                        |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `download.file()`                                          |                 | downloads files directly from websites                                                                                 | Week 7: Downloading and Importing Data                                                |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
| `dir_create()`                                             | fs              | creates a new folder in project folder                                                                                 | Week 7: Downloading and Importing Data                                                |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+
|                                                            |                 |                                                                                                                        |                                                                                       |
+------------------------------------------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+

## Data Manipulation & Summarization

+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| Function                  | Package   | Purpose / Use                                                                                                                                                                                                                                           | Lesson / Additional Resources     |
+===========================+===========+=========================================================================================================================================================================================================================================================+===================================+
| `select(var)`             | tidyverse | selects specified variables from dataframe                                                                                                                                                                                                              | Week 2: select()                  |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | in argument, can use:                                                                                                                                                                                                                                   |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   single variable                                                                                                                                                                                                                                     |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   multiple vars, separated by comma                                                                                                                                                                                                                   |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   contains("")                                                                                                                                                                                                                                        |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   starts_with("")                                                                                                                                                                                                                                     |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   ends_with("")                                                                                                                                                                                                                                       |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   var:var (selects range of vars)                                                                                                                                                                                                                     |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   -var (drops var)                                                                                                                                                                                                                                    |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `filter()`                | tidyverse | selects subset of observations, using comparison operators (==, !=, \>, \>=, \<, \<=, is.na, !is.na, %in%) and logical operators (&, \|, !)                                                                                                             | Week 2: filter()                  |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   `filter(var == 10)`                                                                                                                                                                                                                                 |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   `filter(is.na(var))`                                                                                                                                                                                                                                |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `drop_na()`               | tidyverse | in addition to `filter(!is.na())`, `drop_na()` can be used to remove observations with NA values                                                                                                                                                        | Week 2: filter()                  |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `mutate()`                | tidyverse | makes or changes existing vars:                                                                                                                                                                                                                         | Week 2: mutate()                  |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   to make var w/ specific value: `mutate(var = "")`                                                                                                                                                                                                   | Week 7: Changing Variable Types   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   to make a new var based on other vars: `mutate(var1 = var * 2)`                                                                                                                                                                                     | Week 7: Tidy Data Rule #3         |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | -   to change an existing var: `mutate(var = var + 1)`                                                                                                                                                                                                  | Week 7: Dealing with Missing Data |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           |     -   to change var type: `mutate(var = as.numeric(var))` `mutate(var = as.character(var))`                                                                                                                                                           | Week 3: session                   |
|                           |           |     -   to remove a string of text: `mutate(var = str_remove(var,pattern = "text to remove"))`                                                                                                                                                          |                                   |
|                           |           |     -   to recode specified values: `mutate(var = recode(var,"old value" = "new value"))`                                                                                                                                                               |                                   |
|                           |           |     -   to modify value based on a condition: `mutate(var = if_else(var == "some_value",true = "if_true_value",false = "else_value"))`                                                                                                                  |                                   |
|                           |           |     -   to modify value based on multiple conditions: `mutate(var = case_when(var == "some value" ~ "new value",var == "some B value" ~ "new B value",var == "some C value" ~ "new C value",.default = "value for all others that don't match above"))` |                                   |
|                           |           |     -   to remove non-numeric characters and convert var to numeric: `mutate(var = parse_number(var))`                                                                                                                                                  |                                   |
|                           |           |     -   to set value as NA based on condition: `mutate(var = na_if(var, "condition"))`                                                                                                                                                                  |                                   |
|                           |           |     -   to change cell value from NA to specified value: `mutate(var = replace_na(var, "value to replace"))`                                                                                                                                            |                                   |
|                           |           |     -   to wrap text (to be used with plot labels): `mutate(var_wrapped = str_wrap(var, width = Xwidth))`                                                                                                                                               |                                   |
|                           |           |     -   to reorder a var for a plot: `mutate(var = fct_relevel(var, "cell value1", "cell value2", "cell value3"))` or `mutate(plottedvar = fct_relevel(plottedvar, var_to_order_by))`                                                                   |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `group_by()`              | tidyverse | groups data by a specified variable, often used with `summarize()`                                                                                                                                                                                      | Week 2: group_by()                |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | `group_by(varX) |>summarize(mean_varY = mean(varY, na.rm = TRUE))`                                                                                                                                                                                      |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `summarize()`             | tidyverse | summarizes a variable based on specified argument, for example: `summarize(mean_var = mean(var))`                                                                                                                                                       | Week 2: summarize()               |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | must remove NA values using `drop_na(var)` or in argument: `summarize(mean_var = mean(var, na.rm = TRUE))`                                                                                                                                              |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | can have multiple summaries in one function: `summarize(mean_var = mean(var, na.rm = TRUE),max_var = max(var, na.rm = TRUE))`                                                                                                                           |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | can be used with `group_by()` or can add argument within summarize: `summarize(mean_var = mean(var, na.rm = TRUE),.by = c(var1, var2))`                                                                                                                 |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `count()`                 | tidyverse | counts observations based on specified variable                                                                                                                                                                                                         | Week 2: group_by()                |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `tably(var, var)`         | janitor   | produces crosstab                                                                                                                                                                                                                                       | Week 2: session                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `arrange()`               | tidyverse | sorts dataset based on specified variables, in ascending order by default                                                                                                                                                                               | Week 2: arrange()                 |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | to sort in descending order, use `arrnge(desc(var))`                                                                                                                                                                                                    |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `pivot_longer()`          | tidyverse | reshapes long                                                                                                                                                                                                                                           | Week 7: Tidy Data Rule #1         |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | `pivot_longer(cols = cols_to_use,names_to = "name_of_identifier_var",values_to = "name_of_value_var")`                                                                                                                                                  |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `separate_longer_delim()` |           | reshapes data based on multiselect variable, such that one row = one response option                                                                                                                                                                    |                                   |
|                           |           |                                                                                                                                                                                                                                                         |                                   |
|                           |           | `separate_longer_delim(variable,delim = ", ")`                                                                                                                                                                                                          |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `slice_max()`             |           |                                                                                                                                                                                                                                                         | Week 9: lesson                    |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `pull()`                  |           |                                                                                                                                                                                                                                                         | Week 9: lesson                    |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+
| `str_glue("{var} text")`  |           |                                                                                                                                                                                                                                                         |                                   |
+---------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------+

## Visualizations

+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| Function               | Package                                                                                       | Purpose                                                                                                 | Lesson / Additional Resources                                                                   |
+========================+===============================================================================================+=========================================================================================================+=================================================================================================+
| `ggplot() +`           | tidyverse                                                                                     | select splot data and sets aesthetic properties (x, y, color, fill, etc) using the following arguments: | Week 3                                                                                          |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | -   `data = data_name,`                                                                                 |                                                                                                 |
|                        |                                                                                               | -   `mapping = aes(x = var, y = var)) +`                                                                |                                                                                                 |
|                        |                                                                                               | -   `color = var` -- changes outline color                                                              |                                                                                                 |
|                        |                                                                                               | -   `fill = var`                                                                                        |                                                                                                 |
|                        |                                                                                               | -   `label = var` - must be used with `geom_text()`                                                     |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `geom_point()`         | tidyverse                                                                                     | produces scatterplot                                                                                    | Week 3: Scatterplots                                                                            |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `geom_histogram()`     | tidyverse                                                                                     | produces histogram, using stat = "bin" as default statistical calculation                               | Week 3: Histograms                                                                              |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | can add argument `bins = 10` to manually set \# of bins - default is 30 bins                            |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `geom_bar()`           | tidyverse                                                                                     | produces bar chart, where the default statistical transformation is count                               | Week 3: Bar Charts                                                                              |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | if data has already been summarized, add argument `stat = "identity"`                                   |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `geom_col()`           | tidyverse                                                                                     | produces bar chart, where data has already been summarized                                              | Week 3: Setting color and fill scales                                                           |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | if data is grouped, default is stacked bars; use argument `position = "dodge"` to set bars side by side | Week 3: Plot labels                                                                             |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | additional arguments:                                                                                   |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | -   `show.legend = FALSE` to remove legend                                                              |                                                                                                 |
|                        |                                                                                               | -   `width = 0.9` - sets bar width at 90% of space                                                      |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `geom_chicklet()`      | ggchicklet                                                                                    |                                                                                                         | Week 9: session                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `geom_line()`          | tidyverse                                                                                     | produces line chart                                                                                     | Week 3: session                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | needs to be used to with argument `group = var` to organize data for lines                              |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `coord_flip()`         | tidyverse                                                                                     | flips x and y vars                                                                                      | Week 3: Bar Charts                                                                              |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `scale_color_manual()` | tidyverse                                                                                     | manually specifies colors to use in plot                                                                | Week 3: Setting color and fill scales                                                           |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | `scale_color_manual(values = c(HEX, HEX, HEX))`                                                         |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `scale_color_...()`    | tidyverse                                                                                     | uses built-in color palettes                                                                            | Week 3: Bar Charts                                                                              |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | can use argument `option = ""` to select specific palette                                               |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | use `_c` or `_d` in function name to specify whether data is discrete or continuous                     |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `scale_y_...()`        | tidyverse                                                                                     | used with a number of arguments to format axes                                                          | Week 3: Setting x and y scales                                                                  |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | -   `limits = c(x, x)` - sets min and max values for axis                                               |                                                                                                 |
|                        |                                                                                               | -   `breaks = c(0, 5, 10, 15)` - for continuous data, labels axis                                       |                                                                                                 |
|                        |                                                                                               | -   `labels = c("", "", "")` - for discrete data, labels axis                                           |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | use `_continuous` or `_discrete` in function name to match var type                                     |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `scale_x_...()`        | tidyverse                                                                                     | used with a number of arguments to format axes                                                          | Week 3: Setting x and y scales                                                                  |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | -   `limits = c(x, x)` - sets min and max values for axis                                               |                                                                                                 |
|                        |                                                                                               | -   `breaks = c(0, 5, 10, 15)` - for continuous data, labels axis                                       |                                                                                                 |
|                        |                                                                                               | -   `labels = c("", "", "")` - for discrete data, labels axis                                           |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | use `_continuous` or `_discrete` in function name to match var type                                     |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `geom_text()`          | tidyverse                                                                                     | adds data labels, where label var has been set as argument in `ggplot()`                                | Week 3: Adding text to plots                                                                    |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | possible arguments:                                                                                     |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | -   `vjust = 0` - puts label on outer edge of vertical bars                                             |                                                                                                 |
|                        |                                                                                               | -   `vjust = 1` - puts label on inner edge of vertical bars                                             |                                                                                                 |
|                        |                                                                                               | -   `hjust` - used for horizontal justification                                                         |                                                                                                 |
|                        |                                                                                               | -   `position=position_stack(vjust=0.5))` - places label in center of bar                               |                                                                                                 |
|                        |                                                                                               | -   `color = HEX` - changes text color                                                                  |                                                                                                 |
|                        |                                                                                               | -   `fill = HEX` - changes background color                                                             |                                                                                                 |
|                        |                                                                                               | -   `size` - sets label size in mm; can use `size = X / .pt)` to set size relative to points            |                                                                                                 |
|                        |                                                                                               | -   `fontface` - font settings, like "bold"                                                             |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `labs()`               | tidyverse                                                                                     | adds labels to plot, using the following arguments:                                                     | Week 3: Plot labels                                                                             |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | -   `title = "",`                                                                                       |                                                                                                 |
|                        |                                                                                               | -   `subtitle = "",`                                                                                    |                                                                                                 |
|                        |                                                                                               | -   `caption = "",`                                                                                     |                                                                                                 |
|                        |                                                                                               | -   `x = "",`                                                                                           |                                                                                                 |
|                        |                                                                                               | -   `y = "",`                                                                                           |                                                                                                 |
|                        |                                                                                               | -   `fill = "",` - changes legend title                                                                 |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | use "NULL" to remove label                                                                              |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `theme_...()`          | tidyverse, [ggthemes](https://yutannihilation.github.io/allYourFigureAreBelongToUs/ggthemes/) | this set of functions changes the overall theme of a plot                                               | Week 3: Themes                                                                                  |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | use `theme_void()` to remove themes                                                                     |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | possible arguments:                                                                                     |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | -   `base_size = X` sets text size across plot                                                          |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `facet_wrap(vars()`    | tidyverse                                                                                     | creates small multiples based on a specified variable                                                   | Week 3: Facets                                                                                  |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | `facet_wrap(vars(sex))`                                                                                 |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `facet_grid()`         | tidyverse                                                                                     | creates small multiples, which can be arranged in columns or rows                                       | Week 3: Facets                                                                                  |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | `facet_grid(rows = vars(year), cols = vars(sex))`                                                       |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `ggpreview()`          | nflplotR                                                                                      | set size of plot and preview                                                                            | Week 6 session, [guide](https://search.r-project.org/CRAN/refmans/nflplotR/html/ggpreview.html) |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
| `ggsave()`             | tidyverse                                                                                     | saves last plot made, using a number of arguments:                                                      | Week 3: Save plots                                                                              |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | -   `filename = ""`                                                                                     |                                                                                                 |
|                        |                                                                                               | -   `height = X` / `width = X` / `units = "in"`                                                         |                                                                                                 |
|                        |                                                                                               | -   `bg = HEX` - sets background color, default is transparent                                          |                                                                                                 |
|                        |                                                                                               | -   `dpi =` - dot per square inch                                                                       |                                                                                                 |
|                        |                                                                                               |                                                                                                         |                                                                                                 |
|                        |                                                                                               | pdf is vector based and doesn't need dpi - will look good                                               |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+
|                        | tidyverse                                                                                     |                                                                                                         |                                                                                                 |
+------------------------+-----------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+

# Tips

-   project workflow
    -   in github, each repo is a project?
-   general
    -   when selecting a file, enter folder name and hit TAB, which will pull up a list of files you can select from
    -   to view the help file for a function, type in the console: ?functionname
-   to create global variables (like for file paths), edit your .Renviron file - see Week 6 session \~38:00
-   tidy data -- more [here](https://openscapes.org/blog/2020-10-12-tidy-data/)
    -   every column is a variable
    -   every row is an observation
    -   every cell is a single value
-   keyboard shortcuts
    -   CMD + shift + M = pipe operator
    -   CMD + shift + C = insert comment#
    -   CTRL + L = clears console
-   [cheatsheets](https://github.com/rfortherestofus/rin3-fall-2023/blob/main/misc/beginner-cheatsheets.pdf)
-   quarto
    -   resources
        -   [markdown basics](https://quarto.org/docs/authoring/markdown-basics.html)
        -   [code block cell options](https://quarto.org/docs/reference/cells/cells-knitr.html)
        -   [custom CSS for HTML](https://quarto.org/docs/output-formats/html-basics.html#css-styles)
        -   [creating a website using quarto](https://quarto-workshop.netlify.app/)
    -   tips
        -   to run an R script at the top of quarto doc (and use cleaned data and plots), include a code chunk with `source("filename.R")`
        -   creating custom look and feel --- depends on output type
            -   for using HTML divs to create columns and manage page layout, see 49:00 of [Lesson 4: session](https://rfortherestofus.com/courses/r-in-3-months-fall-2023/lessons/live-session)
-   [shiny documentation](https://shiny.posit.co/r/gallery/#feature-demos)
